#!/usr/bin/env node
/**
 * <p>Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Please see the LICENSE file for information about licensing.</p>
 *
 * Generates the documentation
 */

var fs = require('fs'),
	path = require('path'),
	wrench = require('wrench'),
	spawn = require('child_process').spawn,
	codeProcessorDir = path.resolve(path.join(__dirname, '..')),
	directoryQueue = [
		path.join(codeProcessorDir, 'lib'),
		path.join(codeProcessorDir, 'plugins')
	],
	fileList = [];

if (fs.existsSync(path.join(codeProcessorDir, 'docs'))) {
	wrench.rmdirSyncRecursive(path.join(codeProcessorDir, 'docs'));
}

while(directoryQueue.length) {
	var dir = directoryQueue.shift(),
		files = fs.readdirSync(dir), file,
		i = 0, len = files.length;

	for(; i < len; i++) {
		file = path.join(dir,files[i]);
		if (fs.statSync(file).isDirectory()) {
			directoryQueue.push(file);
		} else if (file.match(/.js$/) && file != 'Base.js') {
			fileList.push(file);
		}
	}
}
fileList.push(path.join(codeProcessorDir, 'api_cover_page.md'));

spawn('jsdoc', ['--destination', path.join(codeProcessorDir, 'docs')].concat(fileList), {
	stdio: 'inherit'
});